apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-no-dockerfile-ladd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-no-dockerfile-ladd
    app.kubernetes.io/part-of: test-app-598
  name: nodejs-no-dockerfile-ladd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: nodejs-no-dockerfile-ladd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: nodejs-no-dockerfile-ladd
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-598/nodejs-no-dockerfile-ladd@sha256:2bbb4711567e219e56d2f1afb87d7f435389eb3de5b8e08db1e5380e4ae4f100
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
