apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-zgur
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-zgur
    app.kubernetes.io/part-of: test-app-598
  name: devfile-sample-python-basic-zgur
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-zgur
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-zgur
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/build-templates-e2e/test-app-598/devfile-sample-python-basic-zgur@sha256:27dbbfe2a7ac1a22d5e2ab06a0d39a8dee459fa9fddfc34f3937402dc32fc136
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
